name: Local Runner

on: [push]

jobs:
  local_runner_job:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run PowerShell Script Locally
      run: |
        # Set the path to your PowerShell script
        $scriptPath = "C:\Tosca_Projects\Tosca_Workspaces\PoV\CI.ps1"
        
        # Run the PowerShell script
        powershell -ExecutionPolicy Bypass -File $scriptPath
